
server:
  port: 8080

user:
  defaultHeadPic:
    - http://game.pool9527.com/avatar/1.png
    - http://game.pool9527.com/avatar/2.png
    - http://game.pool9527.com/avatar/3.png
    - http://game.pool9527.com/avatar/4.png
    - http://game.pool9527.com/avatar/5.png
    - http://game.pool9527.com/avatar/6.png
    - http://game.pool9527.com/avatar/7.png
    - http://game.pool9527.com/avatar/8.png
    - http://game.pool9527.com/avatar/9.png
    - http://game.pool9527.com/avatar/10.png
    - http://game.pool9527.com/avatar/11.png
    - http://game.pool9527.com/avatar/12.png
    - http://game.pool9527.com/avatar/13.png
    - http://game.pool9527.com/avatar/14.png
    - http://game.pool9527.com/avatar/15.png
    - http://game.pool9527.com/avatar/16.png
    - http://game.pool9527.com/avatar/17.png
    - http://game.pool9527.com/avatar/18.png
    - http://game.pool9527.com/avatar/19.png
    - http://game.pool9527.com/avatar/20.png
  receiveLimit: 1000
  receiveCount: 3
  signatureMessage: test
  receiveAmount: 1000
  signatureVerifyHost: https://aleo123.io/api/v3/aleo/programs/signature/verify
  defaultBalance: 3000




argon2:
  iterations: 2
  key_length: 32
  salt_length: 16
  memory: 64
  parallelism: 4

redis:
  host: localhost
  port: 6379
  password:
  database_index: 0

smtp:
  host: smtp.qq.com
  port: 25
  timeout: 10s
  username: 1101375579@qq.com
  password: zvogtpjcpltohbif
  sender: Game3CardPoker<1101375579@qq.com>
  subject: Registration verification code